export default [
  "Aksharadhipati",
  "Surahd samrat",
  "Swadharmyukt",
  "Karunanidhi",
  "Saral",
  "Guru bhakt",
  "Para bhakti",
  "Prabhu bhakti",
  "Sarvedeshiyata",
  "Atmiya Samrat",
  "Khandan",
  "Sambandh yog",
  "Sahajta",
  "Krupa sindhu",
  "Dayalu",
  "Atmalakshi",
  "Nirpekshta",
  "Dasatva",
  "Nirmani",
  "Nirbhayta",
  "Aatmgyani",
  "Garibahi",
  "Nirlep",
  "Nirdosh budhhi",
  "Haridham ",
  "Suruchi ",
  "Premal",
  "Vadhu padtu kam kare",
  "Karkasar yukt jivan",
  "Mathe padine jive",
  "Sarvopari",
  "Nih swadi",
  "Garju",
  "Nih swarthi",
  "Zero avastha",
  "Kalyankari",
  "Hitkari",
  "Mangalkari",
  "Rasgan murti",
  "Prerak",
  "Pravartak",
  "Nishkami",
  "Nishkrodhi",
  "Ekantik",
  "Kartaharta",
  "Sarvopari",
  "Sarve niyanta",
  "KUSHAGRA BUDDHI",
  "Positive vicharo grahan karnar",
  "Bhulku",
  "SEVABHAKTI",
  "sweekar",
  "Bahya drashti zero",
  "Divyata",
  "Sarvottam sadhak",
  "Abhav avgun ma na jai",
  "Mahima pradhan",
  "Chaitanya shilpi",
  "SADHAK",
  "Desh bhakti",
  "Niyamit swadhyay",
  "Bhajanik",
  "Vinamra",
  "Ekagrta",
  "Aagyakari",
  "Bhakt Vatsal",
  "Jagrat",
  "Nirvikalp",
  "Rakshanhar",
  "SahajAanand",
  "Taranhar",
  "Vivek",
  "Gun grahak",
  "Stithpragnya",
  "Potano dosh jonar",
  "Dehbhav thi par",
  "Samp",
  "Udarta",
  "Ekta",
  "Shurveerta",
  "Sahanshilta",
  "Dhairyavan",
  "Badhane potanaj lage",
  "Mayathi par",
  "Badhane het karnar",
  "Das na das",
  "Sacha mavtar",
  "Subh chintak",
  "Sant priya",
  "Sarthi",
  "Bhagwanni prasanta",
  "Bhagwati ",
  "Atmabuddhi",
  "Gunatit priti",
  "Ahobhav",
  "Vachnamrut",
  "Swamini vaato",
  "Akshardham",
  "Prabhudas bhai",
  "Sevak"
];
